import {Dimensions, Platform, StyleSheet} from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';
import Colors from './colors';

export const GlobalStyles = StyleSheet.create({
  mainView: {
    backgroundColor: Colors.light_white,
    flex: 1,
  },
  contentView: {
    marginHorizontal: wp('4%'),
  },
  boxHeading: {
    flex: 0.5,
    fontSize: wp('4%'),
    // fontFamily: Fonts.Font_Bold,
    textAlign: 'left',
  },
  viewAll: {
    flex: 0.5,
    fontSize: wp('3.4%'),
    // fontFamily: Fonts.Font_Semibold,
    textTransform: 'uppercase',
    color: Colors.link_color,
    textAlign: 'right',
    padding: 8,
  },
  outstockview: {
    backgroundColor: Colors.red,
    padding: wp('0.8%'),
    width: wp('18%'),
    position: 'absolute',
    top: hp('1.2%'),
    justifyContent: 'center',
    alignItems: 'center',
    left: wp('2%'),
    overflow: 'hidden',
    shadowColor: 'black',
    shadowOffset: {width: 0, height: 0.3},
    shadowOpacity: 0.25,
    shadowRadius: 3,
    borderRadius: wp('1%'),
    elevation: 3,
  },
  outofstockTxt: {
    color: Colors.white,
    // fontFamily: Fonts.Font_Semibold,
    fontSize: wp('2.6%'),
    textAlign: 'center',
  },
  newtextView: {
    backgroundColor: Colors.white,
    padding: wp('0.8%'),
    width: wp('12%'),
    position: 'absolute',
    top: hp('1.2%'),
    left: wp('2%'),
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    shadowColor: 'black',
    shadowOffset: {width: 0, height: 0.3},
    shadowOpacity: 0.25,
    shadowRadius: 3,
    borderRadius: wp('1%'),
    elevation: 3,
  },
  newTxt: {
    color: Colors.text_color,
    // fontFamily: Fonts.Font_Semibold,
    fontSize: wp('2.8%'),
    textAlign: 'center',
  },
  unFavIcon: {
    fontWeight: '700',
    fontSize: wp('3.8%'),
  },
  headerLeft: {
    flex: 0.1,
    marginLeft: wp('5%'),
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerCenter: {
    flex: 0.8,
    marginLeft: wp('5%'),
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  headingTxt: {
    // fontFamily: Fonts.Font_Bold,
    fontSize: wp('5.5%'),
    color: Colors.text_color,
  },
  horizontalLine: {
    width: wp('85%'),
    alignSelf: 'center',
    height: 0.5,
    backgroundColor: Colors.line_color,
  },
  tabBarView: {
    backgroundColor: Colors.light_white,
    alignItems: 'center',
    justifyContent: 'center',
    width: wp('100%'),
    height: Platform.OS === 'ios' ? wp('22%') : wp('15%'),
    flexDirection: 'row',
    marginTop: hp('1%'),
  },
  tabbarText: {
    alignSelf: 'center',
    fontSize: Platform.isPad === true ? wp('3%') : wp('5%'),
    marginLeft: Platform.isPad === true ? wp('1%') : wp('2%'),
    // fontFamily: Fonts.Font_Bold,
    flex: 1,
    color: Colors.text_color,
  },
  authtabbarText: {
    alignSelf: 'center',
    fontSize: Platform.isPad === true ? hp('3%') : hp('4%'),
    textAlign: 'center',
    fontFamily: 'Poppins-SemiBold',
    // flex: 1,
    // color: '#342B68',
    backgroundColor: Colors.white,
    // lineHeight: hp('5%'),
    fontWeight: 'bold',
    width: wp('80%'),
  },
  authSubText: {
    fontSize: Platform.isPad === true ? wp('3%') : hp('1.8%'),
    fontFamily: 'Poppins-Regular',
    textAlign: 'center',
    // color: '#000',
  },
  mainProductView: {
    backgroundColor: Colors.light_white,
    // flex: 0.5,
    height: Platform.isPad === true ? wp('50%') : wp('75%'),
    width: Platform.isPad === true ? wp('30%') : wp('46%'),
    // margin: wp('2%'),
    marginBottom: wp('3%'),
    marginRight: wp('3%'),
    borderRadius: wp('2%'),

    // mange Shadow
    shadowColor: 'black',
    shadowOffset: {width: 0, height: 0.3},
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 5,
    // shadowOpacity: Platform.OS === 'ios' ? 0.20 : 10,
    // shadowRadius: 5,
    // shadowOffset: { height: 0, weight: 0 },
    // shadowColor: 'black',
    // elevation: 10,
  },
  mainCategoriesView: {
    backgroundColor: Colors.light_white,
    // flex: Platform.isPad === true ? 1 : 0.5,
    height: Platform.isPad === true ? wp('45%') : wp('60%'),
    width: Platform.isPad === true ? wp('30%') : wp('46%'),
    // margin: wp('2%'),
    marginBottom: wp('3%'),
    marginRight: wp('3%'),
    borderRadius: wp('2%'),

    // mange Shadow
    shadowColor: 'black',
    shadowOffset: {width: 0, height: 0.3},
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 5,
    // shadowOpacity: Platform.OS === 'ios' ? 0.10 : 10,
    // shadowRadius: 2,
    // shadowColor: 'black',
  },
  mainWishProductView: {
    // flex: 0.5,
    padding: Platform.isPad === true ? wp('1.5%') : wp('3%'),
    alignItems: 'center',
    flexDirection: 'row',
    borderBottomWidth: wp('0.1%'),
    borderColor: Colors.dark_gray_text,
    borderRadius: wp('2%'),

    // mange Shadow
    // shadowOpacity: Platform.OS === 'ios' ? 0.20 : 10,
    // shadowRadius: 5,
    // shadowColor: 'black',
    // elevation: 10,
  },
  button: {
    // height: Platform.isPad === true ? wp('6%') : wp('11%'),
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    shadowColor: 'rgba(0,0,0, .4)',
    shadowOffset: {height: 1, width: 1},
    shadowOpacity: 1,
    shadowRadius: 1,
    elevation: 2,
  },
  buttonText: {
    // fontFamily: 'Poppins-SemiBold',
    textAlign: 'center',
    color: Colors.white,
    fontSize: Platform.isPad === true ? wp('2.5%') : hp('1.6%'),
  },
  textInputStyle: {
    height: wp('12%'),
    fontFamily: 'Poppins-Regular',
    // backgroundColor: '#F6F9FC',
    backgroundColor: Colors.white,
    fontSize: Platform.isPad === true ? wp('3.5%') : hp('1.6%'),
    color: Colors.secondry_text_color,
    padding: 5,
  },
  textAreaInputStyle: {
    height: wp('20%'),
    // backgroundColor: '#F6F9FC',
    backgroundColor: Colors.white,
    fontSize: Platform.isPad === true ? wp('3.5%') : wp('3.2%'),
    color: Colors.secondry_text_color,
    padding: 5,
    // borderColor: Colors.light_gray
  },
  textInputStyle2: {
    height: wp('15%'),
    padding: 5,
    // fontFamily: Fonts.Font_Segoe_UI_Reguler,
    backgroundColor: Colors.white,
    width: wp('44%'),
    color: Colors.black,
  },
  shadowInput: {
    elevation: 4,
  },
  authHeader: {
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    marginTop: hp('1.5%'),
  },
  // Home screen global view ------------------------------------------------------------- >>>>>>>>>>
  mainViewHomeProduct: {
    backgroundColor: Colors.light_white,
    width: Platform.isPad === true ? wp('30%') : wp('40%'),
    height: Platform.isPad === true ? wp('50%') : wp('70%'),
    margin: Platform.isPad === true ? wp('1.5%') : wp('2%'),
    borderRadius: wp('2%'),

    // mange Shadow
    shadowColor: 'black',
    shadowOffset: {width: 0, height: 0.3},
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 5,
    // shadowOpacity: Platform.OS === 'ios' ? 0.10 : 10,
    // shadowRadius: 2,
    // shadowColor: 'black',
  },
  gridViewHomeProduct: {
    backgroundColor: Colors.lightYellowBackground,
    flex: 0.5,
    height: wp('50%'),
    margin: wp('2%'),
    borderRadius: wp('2%'),
    // mange Shadow
    shadowOpacity: Platform.OS === 'ios' ? 0.1 : 10,
    shadowRadius: 2,
    shadowColor: 'black',
    elevation: 10,
  },
  gridMainView: {
    backgroundColor: Colors.white,
    paddingVertical: wp('3%'),
    // mange Shadow
    shadowOpacity: Platform.OS === 'ios' ? 0.1 : 10,
    shadowRadius: 2,
    shadowColor: 'black',
    elevation: 10,
  },
  TopBrandView: {
    backgroundColor: Colors.white,
    width: wp('40%'),
    height: wp('70%'),
    margin: wp('2%'),
    borderRadius: wp('2%'),
    // mange Shadow
    shadowOpacity: Platform.OS === 'ios' ? 0.1 : 10,
    shadowRadius: 2,
    shadowColor: 'black',
    elevation: 10,
  },
  mainViewHomeProductHeader: {
    // flex: 1,
    paddingHorizontal: wp('3%'),
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  mainTextHomeProductHeader: {
    fontSize: Platform.isPad === true ? wp('3%') : wp('4.5%'),
    // fontFamily: Fonts.Font_Segoe_UI_Bold,
    // flex: 1,
  },
  seeAllTextHomeProduct: {
    fontSize: Platform.isPad === true ? wp('2.5%') : wp('4%'),
    // fontFamily: Fonts.Font_Segoe_UI_Semibold,
    // color: Colors.black
  },

  loader: {
    marginVertical: Dimensions.get('screen').height / 3,
  },
  badge: {
    position: 'absolute',
    top: -14,
    right: 3,
    height: 24,
    width: 24,
    borderRadius: 12,
    backgroundColor: Colors.themeColor,
    justifyContent: 'center',
  },
  badgeText: {
    color: Colors.white,
    textAlign: 'center',
    fontSize: wp('3%'),
    // fontFamily: Fonts.Font_Semibold,
  },
});
